name = "rp2040_hal"
description = "Drivers and HAL for the RP2040 micro-controller family"
version = "0.1.0"
licenses = ["BSD 3-Clauses"]

authors = ["Jeremy Grosser"]
maintainers = ["Jeremy Grosser <jeremy@synack.me>"]
maintainers-logins = ["JeremyGrosser"]
tags = ["embedded", "nostd", "rp2040", "raspberrypi", "drivers"]
website = "https://github.com/JeremyGrosser/rp2040_hal"

[[depends-on]]
cortex_m = "^0.3.0"
hal = "^0.1.0"

[origin]
commit = "aad1ec114a554f433d39bd1a234163b1b2bbab52"
url = "git+https://github.com/JeremyGrosser/rp2040_hal.git"

